import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "../storeProvider/StoreProvider";
// import PopupLayout from "@/components/PopupLayout";
import SignupModal from "@/components/SignupModal";
import AuthProvider from "@/components/auth/AuthProvider";
// import Navbar from "@/components/common/NavBar";
import ToasterProvider from "@/components/common/ToasterProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YuvaX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthProvider>
            {/* <Navbar /> */}
            <ToasterProvider />
            {children}
            {/* Global auth modal so Login/Sign Up buttons work across all pages */}
            <SignupModal />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}